name: build-test

on:
  pull_request:
    paths-ignore:
      - '**.md'    
  push:    
    paths-ignore:
      - '**.md'
      
jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        # 10.x, 12.x,
        node-version: [ 12.x]
        operating-system: [ubuntu-latest, windows-latest, macos-latest,'windows-latest']
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - uses: jiro4989/setup-nim-action@v1
      - name: Install nim deps
        run: nimble install -d -y
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install node deps
        run: |
          yarn global add node-gyp
          yarn install --ignore-scripts
        working-directory: test
      - name: test
        run: nimble test
      - name: build
        run: yarn build
        working-directory: test
      - name: publish
        working-directory: test
        env:
          PREBUILD_TOKEN: ${{ secrets.PREBUILD_TOKEN }}
        run: yarn prebuild --upload-all -u ${{ secrets.PREBUILD_TOKEN }}